namespace Axon.Core.Domain;

/// <summary>
/// The canonical Axon Common Schema (ACS) record.
/// Every biometric measurement from every vendor is normalised into this
/// single immutable structure at the ingestion boundary (IBiometricDriver).
///
/// Design invariants:
///   • All fields except <see cref="CorrelationId"/> are non-nullable.
///   • <see cref="Value"/> is always in SI / ACS-defined units; no vendor
///     native units survive past the NormalizationMapper.
///   • <see cref="Id"/> is generated by the driver, not the DB.
/// </summary>
/// <param name="Id">Deterministic GUID derived from (DeviceId + Timestamp + Type).</param>
/// <param name="Timestamp">UTC event time at the moment of measurement.</param>
/// <param name="Type">ACS biometric category.</param>
/// <param name="Value">Measurement value in ACS canonical units.</param>
/// <param name="Unit">Human-readable SI unit string (e.g. "bpm", "ms", "%", "W").</param>
/// <param name="Source">Provenance descriptor.</param>
/// <param name="CorrelationId">
///     Optional opaque token used by the Transactional Outbox to group
///     related events emitted in a single sync batch.
/// </param>
public sealed record BiometricEvent(
    Guid            Id,
    DateTimeOffset  Timestamp,
    BiometricType   Type,
    double          Value,
    string          Unit,
    SourceMetadata  Source,
    string?         CorrelationId = null)
{
    /// <summary>
    /// PII Shield: suppress raw biometric value and device identity in logs.
    /// </summary>
    public override string ToString() =>
        $"BiometricEvent {{ Id={Id}, Type={Type}, Timestamp={Timestamp:O}, Value=[REDACTED] }}";
}
