// <auto-generated />
using System;
using Axon.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Axon.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AxonDbContext))]
    [Migration("20260410055400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("Axon.Infrastructure.Persistence.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedEntityId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CallerIdentity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Operation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AffectedEntityId")
                        .HasDatabaseName("IX_AuditLog_EntityId");

                    b.HasIndex("OccurredAtUnixMs")
                        .HasDatabaseName("IX_AuditLog_OccurredAt");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("Axon.Infrastructure.Persistence.Entities.BiometricEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("BiometricType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Type");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("IngestionTimestampUnixMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IngestionMs");

                    b.Property<long>("TimestampUnixMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TimestampMs");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_BiometricEvents_CorrelationId");

                    b.HasIndex("BiometricType", "TimestampUnixMs")
                        .HasDatabaseName("IX_BiometricEvents_Type_Timestamp");

                    b.ToTable("BiometricEvents", (string)null);
                });

            modelBuilder.Entity("Axon.Infrastructure.Persistence.Entities.SyncOutboxEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BiometricEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProcessedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerializedPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUnixMs")
                        .HasDatabaseName("IX_SyncOutbox_CreatedAt");

                    b.HasIndex("ProcessedAtUnixMs")
                        .HasDatabaseName("IX_SyncOutbox_Pending");

                    b.ToTable("SyncOutbox", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
